version: "3"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    tty: true
    restart: unless-stopped

  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    links:
      - app:app
    environment:
      DOMAINS: 'api.nascalay.trasta.dev -> http://app:3000'
      STAGE: 'local'
      FORCE_RENEW: 'false'
      WEBSOCKET: 'true'
      CLIENT_MAX_BODY_SIZE: 0
    restart: unless-stopped
    volumes:
      - https-portal_data:/var/lib/https-portal

volumes:
  https-portal_data: