openapi: 3.0.2
info:
  title: FastAPI
  version: 0.1.0
servers:
  - url: 'http://localhost:8000'
    description: local
paths:
  /:
    get:
      summary: Read Root
      operationId: read_root__get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /expression/{date}:
    get:
      summary: Get Equal Daily
      operationId: get_equal_daily_expression__date__get
      parameters:
        - required: true
          schema:
            title: Date
            type: integer
          name: date
          in: path
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PosEqual'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
    post:
      summary: Post Expression Daily
      operationId: post_expression_daily_expression__date__post
      parameters:
        - required: true
          schema:
            title: Date
            type: integer
          name: date
          in: path
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Expression'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Check'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /expression/random/{seed}:
    get:
      summary: Get Equal Random
      operationId: get_equal_random_expression_random__seed__get
      parameters:
        - required: true
          schema:
            title: Seed
            type: integer
          name: seed
          in: path
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PosEqual'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
    post:
      summary: Post Expression Random
      operationId: post_expression_random_expression_random__seed__post
      parameters:
        - required: true
          schema:
            title: Seed
            type: integer
          name: seed
          in: path
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Expression'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Check'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    Check:
      title: Check
      type: object
      properties:
        check:
          title: Check
          type: array
          items:
            type: integer
          default: []
    Expression:
      title: Expression
      required:
        - expression
      type: object
      properties:
        expression:
          title: Expression
          type: string
    HTTPValidationError:
      title: HTTPValidationError
      type: object
      properties:
        detail:
          title: Detail
          type: array
          items:
            $ref: '#/components/schemas/ValidationError'
    PosEqual:
      title: PosEqual
      required:
        - pos
      type: object
      properties:
        pos:
          title: Pos
          type: integer
    ValidationError:
      title: ValidationError
      required:
        - loc
        - msg
        - type
      type: object
      properties:
        loc:
          title: Location
          type: array
          items:
            anyOf:
              - type: string
              - type: integer
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
